import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'injection.config.dart';

final getIt = GetIt.instance;

@InjectableInit(
  initializerName: r'$initGetIt', // The default name generated by injectable
  preferRelativeImports: true,
  asExtension: false, // Important: Set to false to use the global function
)
void configureDependencies() => $initGetIt(getIt);

@module
class RegisterModule {
  // Register your dependencies here
  // Example:
  // @lazySingleton
  // ApiClient get apiClient => ApiClient();
}
